/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as MainRouteImport } from './app/_main'
import { Route as AuthRouteImport } from './app/_auth'
import { Route as SplatRouteImport } from './app/$'
import { Route as MainIndexRouteImport } from './app/_main/index'
import { Route as MainSettingsRouteImport } from './app/_main/settings'
import { Route as MainSearchRouteImport } from './app/_main/search'
import { Route as MainExploreRouteImport } from './app/_main/explore'
import { Route as MainUsernameRouteImport } from './app/_main/$username'
import { Route as AuthVerifyEmailRouteImport } from './app/_auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './app/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './app/_auth/register'
import { Route as AuthLoginRouteImport } from './app/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './app/_auth/forgot-password'
import { Route as MainUsernameIndexRouteImport } from './app/_main/$username/index'
import { Route as MainUsernameRepoRouteImport } from './app/_main/$username/$repo'
import { Route as MainUsernameRepoIndexRouteImport } from './app/_main/$username/$repo/index'
import { Route as MainUsernameRepoSettingsRouteImport } from './app/_main/$username/$repo/settings'
import { Route as MainUsernameRepoLabelsRouteImport } from './app/_main/$username/$repo/labels'
import { Route as MainUsernameRepoCommitsRouteImport } from './app/_main/$username/$repo/commits'
import { Route as MainUsernameRepoPullsIndexRouteImport } from './app/_main/$username/$repo/pulls/index'
import { Route as MainUsernameRepoProjectsIndexRouteImport } from './app/_main/$username/$repo/projects/index'
import { Route as MainUsernameRepoIssuesIndexRouteImport } from './app/_main/$username/$repo/issues/index'
import { Route as MainUsernameRepoDiscussionsIndexRouteImport } from './app/_main/$username/$repo/discussions/index'
import { Route as MainUsernameRepoTreeSplatRouteImport } from './app/_main/$username/$repo/tree/$'
import { Route as MainUsernameRepoPullsNewRouteImport } from './app/_main/$username/$repo/pulls/new'
import { Route as MainUsernameRepoPullsNumberRouteImport } from './app/_main/$username/$repo/pulls/$number'
import { Route as MainUsernameRepoProjectsProjectIdRouteImport } from './app/_main/$username/$repo/projects/$projectId'
import { Route as MainUsernameRepoIssuesNewRouteImport } from './app/_main/$username/$repo/issues/new'
import { Route as MainUsernameRepoIssuesNumberRouteImport } from './app/_main/$username/$repo/issues/$number'
import { Route as MainUsernameRepoDiscussionsNewRouteImport } from './app/_main/$username/$repo/discussions/new'
import { Route as MainUsernameRepoDiscussionsNumberRouteImport } from './app/_main/$username/$repo/discussions/$number'
import { Route as MainUsernameRepoCommitsBranchRouteImport } from './app/_main/$username/$repo/commits/$branch'
import { Route as MainUsernameRepoBlobSplatRouteImport } from './app/_main/$username/$repo/blob/$'
import { Route as MainUsernameRepoCommitsBranchIndexRouteImport } from './app/_main/$username/$repo/commits/$branch/index'
import { Route as MainUsernameRepoCommitsBranchOidRouteImport } from './app/_main/$username/$repo/commits/$branch/$oid'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRoute,
} as any)
const MainSearchRoute = MainSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MainRoute,
} as any)
const MainExploreRoute = MainExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => MainRoute,
} as any)
const MainUsernameRoute = MainUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => MainRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const MainUsernameIndexRoute = MainUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainUsernameRoute,
} as any)
const MainUsernameRepoRoute = MainUsernameRepoRouteImport.update({
  id: '/$repo',
  path: '/$repo',
  getParentRoute: () => MainUsernameRoute,
} as any)
const MainUsernameRepoIndexRoute = MainUsernameRepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainUsernameRepoRoute,
} as any)
const MainUsernameRepoSettingsRoute =
  MainUsernameRepoSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoLabelsRoute = MainUsernameRepoLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => MainUsernameRepoRoute,
} as any)
const MainUsernameRepoCommitsRoute = MainUsernameRepoCommitsRouteImport.update({
  id: '/commits',
  path: '/commits',
  getParentRoute: () => MainUsernameRepoRoute,
} as any)
const MainUsernameRepoPullsIndexRoute =
  MainUsernameRepoPullsIndexRouteImport.update({
    id: '/pulls/',
    path: '/pulls/',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoProjectsIndexRoute =
  MainUsernameRepoProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoIssuesIndexRoute =
  MainUsernameRepoIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoDiscussionsIndexRoute =
  MainUsernameRepoDiscussionsIndexRouteImport.update({
    id: '/discussions/',
    path: '/discussions/',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoTreeSplatRoute =
  MainUsernameRepoTreeSplatRouteImport.update({
    id: '/tree/$',
    path: '/tree/$',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoPullsNewRoute =
  MainUsernameRepoPullsNewRouteImport.update({
    id: '/pulls/new',
    path: '/pulls/new',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoPullsNumberRoute =
  MainUsernameRepoPullsNumberRouteImport.update({
    id: '/pulls/$number',
    path: '/pulls/$number',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoProjectsProjectIdRoute =
  MainUsernameRepoProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoIssuesNewRoute =
  MainUsernameRepoIssuesNewRouteImport.update({
    id: '/issues/new',
    path: '/issues/new',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoIssuesNumberRoute =
  MainUsernameRepoIssuesNumberRouteImport.update({
    id: '/issues/$number',
    path: '/issues/$number',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoDiscussionsNewRoute =
  MainUsernameRepoDiscussionsNewRouteImport.update({
    id: '/discussions/new',
    path: '/discussions/new',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoDiscussionsNumberRoute =
  MainUsernameRepoDiscussionsNumberRouteImport.update({
    id: '/discussions/$number',
    path: '/discussions/$number',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoCommitsBranchRoute =
  MainUsernameRepoCommitsBranchRouteImport.update({
    id: '/$branch',
    path: '/$branch',
    getParentRoute: () => MainUsernameRepoCommitsRoute,
  } as any)
const MainUsernameRepoBlobSplatRoute =
  MainUsernameRepoBlobSplatRouteImport.update({
    id: '/blob/$',
    path: '/blob/$',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoCommitsBranchIndexRoute =
  MainUsernameRepoCommitsBranchIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainUsernameRepoCommitsBranchRoute,
  } as any)
const MainUsernameRepoCommitsBranchOidRoute =
  MainUsernameRepoCommitsBranchOidRouteImport.update({
    id: '/$oid',
    path: '/$oid',
    getParentRoute: () => MainUsernameRepoCommitsBranchRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof MainIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/$username': typeof MainUsernameRouteWithChildren
  '/explore': typeof MainExploreRoute
  '/search': typeof MainSearchRoute
  '/settings': typeof MainSettingsRoute
  '/$username/$repo': typeof MainUsernameRepoRouteWithChildren
  '/$username/': typeof MainUsernameIndexRoute
  '/$username/$repo/commits': typeof MainUsernameRepoCommitsRouteWithChildren
  '/$username/$repo/labels': typeof MainUsernameRepoLabelsRoute
  '/$username/$repo/settings': typeof MainUsernameRepoSettingsRoute
  '/$username/$repo/': typeof MainUsernameRepoIndexRoute
  '/$username/$repo/blob/$': typeof MainUsernameRepoBlobSplatRoute
  '/$username/$repo/commits/$branch': typeof MainUsernameRepoCommitsBranchRouteWithChildren
  '/$username/$repo/discussions/$number': typeof MainUsernameRepoDiscussionsNumberRoute
  '/$username/$repo/discussions/new': typeof MainUsernameRepoDiscussionsNewRoute
  '/$username/$repo/issues/$number': typeof MainUsernameRepoIssuesNumberRoute
  '/$username/$repo/issues/new': typeof MainUsernameRepoIssuesNewRoute
  '/$username/$repo/projects/$projectId': typeof MainUsernameRepoProjectsProjectIdRoute
  '/$username/$repo/pulls/$number': typeof MainUsernameRepoPullsNumberRoute
  '/$username/$repo/pulls/new': typeof MainUsernameRepoPullsNewRoute
  '/$username/$repo/tree/$': typeof MainUsernameRepoTreeSplatRoute
  '/$username/$repo/discussions/': typeof MainUsernameRepoDiscussionsIndexRoute
  '/$username/$repo/issues/': typeof MainUsernameRepoIssuesIndexRoute
  '/$username/$repo/projects/': typeof MainUsernameRepoProjectsIndexRoute
  '/$username/$repo/pulls/': typeof MainUsernameRepoPullsIndexRoute
  '/$username/$repo/commits/$branch/$oid': typeof MainUsernameRepoCommitsBranchOidRoute
  '/$username/$repo/commits/$branch/': typeof MainUsernameRepoCommitsBranchIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof MainIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/explore': typeof MainExploreRoute
  '/search': typeof MainSearchRoute
  '/settings': typeof MainSettingsRoute
  '/$username': typeof MainUsernameIndexRoute
  '/$username/$repo/commits': typeof MainUsernameRepoCommitsRouteWithChildren
  '/$username/$repo/labels': typeof MainUsernameRepoLabelsRoute
  '/$username/$repo/settings': typeof MainUsernameRepoSettingsRoute
  '/$username/$repo': typeof MainUsernameRepoIndexRoute
  '/$username/$repo/blob/$': typeof MainUsernameRepoBlobSplatRoute
  '/$username/$repo/discussions/$number': typeof MainUsernameRepoDiscussionsNumberRoute
  '/$username/$repo/discussions/new': typeof MainUsernameRepoDiscussionsNewRoute
  '/$username/$repo/issues/$number': typeof MainUsernameRepoIssuesNumberRoute
  '/$username/$repo/issues/new': typeof MainUsernameRepoIssuesNewRoute
  '/$username/$repo/projects/$projectId': typeof MainUsernameRepoProjectsProjectIdRoute
  '/$username/$repo/pulls/$number': typeof MainUsernameRepoPullsNumberRoute
  '/$username/$repo/pulls/new': typeof MainUsernameRepoPullsNewRoute
  '/$username/$repo/tree/$': typeof MainUsernameRepoTreeSplatRoute
  '/$username/$repo/discussions': typeof MainUsernameRepoDiscussionsIndexRoute
  '/$username/$repo/issues': typeof MainUsernameRepoIssuesIndexRoute
  '/$username/$repo/projects': typeof MainUsernameRepoProjectsIndexRoute
  '/$username/$repo/pulls': typeof MainUsernameRepoPullsIndexRoute
  '/$username/$repo/commits/$branch/$oid': typeof MainUsernameRepoCommitsBranchOidRoute
  '/$username/$repo/commits/$branch': typeof MainUsernameRepoCommitsBranchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_main/$username': typeof MainUsernameRouteWithChildren
  '/_main/explore': typeof MainExploreRoute
  '/_main/search': typeof MainSearchRoute
  '/_main/settings': typeof MainSettingsRoute
  '/_main/': typeof MainIndexRoute
  '/_main/$username/$repo': typeof MainUsernameRepoRouteWithChildren
  '/_main/$username/': typeof MainUsernameIndexRoute
  '/_main/$username/$repo/commits': typeof MainUsernameRepoCommitsRouteWithChildren
  '/_main/$username/$repo/labels': typeof MainUsernameRepoLabelsRoute
  '/_main/$username/$repo/settings': typeof MainUsernameRepoSettingsRoute
  '/_main/$username/$repo/': typeof MainUsernameRepoIndexRoute
  '/_main/$username/$repo/blob/$': typeof MainUsernameRepoBlobSplatRoute
  '/_main/$username/$repo/commits/$branch': typeof MainUsernameRepoCommitsBranchRouteWithChildren
  '/_main/$username/$repo/discussions/$number': typeof MainUsernameRepoDiscussionsNumberRoute
  '/_main/$username/$repo/discussions/new': typeof MainUsernameRepoDiscussionsNewRoute
  '/_main/$username/$repo/issues/$number': typeof MainUsernameRepoIssuesNumberRoute
  '/_main/$username/$repo/issues/new': typeof MainUsernameRepoIssuesNewRoute
  '/_main/$username/$repo/projects/$projectId': typeof MainUsernameRepoProjectsProjectIdRoute
  '/_main/$username/$repo/pulls/$number': typeof MainUsernameRepoPullsNumberRoute
  '/_main/$username/$repo/pulls/new': typeof MainUsernameRepoPullsNewRoute
  '/_main/$username/$repo/tree/$': typeof MainUsernameRepoTreeSplatRoute
  '/_main/$username/$repo/discussions/': typeof MainUsernameRepoDiscussionsIndexRoute
  '/_main/$username/$repo/issues/': typeof MainUsernameRepoIssuesIndexRoute
  '/_main/$username/$repo/projects/': typeof MainUsernameRepoProjectsIndexRoute
  '/_main/$username/$repo/pulls/': typeof MainUsernameRepoPullsIndexRoute
  '/_main/$username/$repo/commits/$branch/$oid': typeof MainUsernameRepoCommitsBranchOidRoute
  '/_main/$username/$repo/commits/$branch/': typeof MainUsernameRepoCommitsBranchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/$username'
    | '/explore'
    | '/search'
    | '/settings'
    | '/$username/$repo'
    | '/$username/'
    | '/$username/$repo/commits'
    | '/$username/$repo/labels'
    | '/$username/$repo/settings'
    | '/$username/$repo/'
    | '/$username/$repo/blob/$'
    | '/$username/$repo/commits/$branch'
    | '/$username/$repo/discussions/$number'
    | '/$username/$repo/discussions/new'
    | '/$username/$repo/issues/$number'
    | '/$username/$repo/issues/new'
    | '/$username/$repo/projects/$projectId'
    | '/$username/$repo/pulls/$number'
    | '/$username/$repo/pulls/new'
    | '/$username/$repo/tree/$'
    | '/$username/$repo/discussions/'
    | '/$username/$repo/issues/'
    | '/$username/$repo/projects/'
    | '/$username/$repo/pulls/'
    | '/$username/$repo/commits/$branch/$oid'
    | '/$username/$repo/commits/$branch/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/explore'
    | '/search'
    | '/settings'
    | '/$username'
    | '/$username/$repo/commits'
    | '/$username/$repo/labels'
    | '/$username/$repo/settings'
    | '/$username/$repo'
    | '/$username/$repo/blob/$'
    | '/$username/$repo/discussions/$number'
    | '/$username/$repo/discussions/new'
    | '/$username/$repo/issues/$number'
    | '/$username/$repo/issues/new'
    | '/$username/$repo/projects/$projectId'
    | '/$username/$repo/pulls/$number'
    | '/$username/$repo/pulls/new'
    | '/$username/$repo/tree/$'
    | '/$username/$repo/discussions'
    | '/$username/$repo/issues'
    | '/$username/$repo/projects'
    | '/$username/$repo/pulls'
    | '/$username/$repo/commits/$branch/$oid'
    | '/$username/$repo/commits/$branch'
  id:
    | '__root__'
    | '/$'
    | '/_auth'
    | '/_main'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/_main/$username'
    | '/_main/explore'
    | '/_main/search'
    | '/_main/settings'
    | '/_main/'
    | '/_main/$username/$repo'
    | '/_main/$username/'
    | '/_main/$username/$repo/commits'
    | '/_main/$username/$repo/labels'
    | '/_main/$username/$repo/settings'
    | '/_main/$username/$repo/'
    | '/_main/$username/$repo/blob/$'
    | '/_main/$username/$repo/commits/$branch'
    | '/_main/$username/$repo/discussions/$number'
    | '/_main/$username/$repo/discussions/new'
    | '/_main/$username/$repo/issues/$number'
    | '/_main/$username/$repo/issues/new'
    | '/_main/$username/$repo/projects/$projectId'
    | '/_main/$username/$repo/pulls/$number'
    | '/_main/$username/$repo/pulls/new'
    | '/_main/$username/$repo/tree/$'
    | '/_main/$username/$repo/discussions/'
    | '/_main/$username/$repo/issues/'
    | '/_main/$username/$repo/projects/'
    | '/_main/$username/$repo/pulls/'
    | '/_main/$username/$repo/commits/$branch/$oid'
    | '/_main/$username/$repo/commits/$branch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/search': {
      id: '/_main/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof MainSearchRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/explore': {
      id: '/_main/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof MainExploreRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/$username': {
      id: '/_main/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof MainUsernameRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/$username/': {
      id: '/_main/$username/'
      path: '/'
      fullPath: '/$username/'
      preLoaderRoute: typeof MainUsernameIndexRouteImport
      parentRoute: typeof MainUsernameRoute
    }
    '/_main/$username/$repo': {
      id: '/_main/$username/$repo'
      path: '/$repo'
      fullPath: '/$username/$repo'
      preLoaderRoute: typeof MainUsernameRepoRouteImport
      parentRoute: typeof MainUsernameRoute
    }
    '/_main/$username/$repo/': {
      id: '/_main/$username/$repo/'
      path: '/'
      fullPath: '/$username/$repo/'
      preLoaderRoute: typeof MainUsernameRepoIndexRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/settings': {
      id: '/_main/$username/$repo/settings'
      path: '/settings'
      fullPath: '/$username/$repo/settings'
      preLoaderRoute: typeof MainUsernameRepoSettingsRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/labels': {
      id: '/_main/$username/$repo/labels'
      path: '/labels'
      fullPath: '/$username/$repo/labels'
      preLoaderRoute: typeof MainUsernameRepoLabelsRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/commits': {
      id: '/_main/$username/$repo/commits'
      path: '/commits'
      fullPath: '/$username/$repo/commits'
      preLoaderRoute: typeof MainUsernameRepoCommitsRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/pulls/': {
      id: '/_main/$username/$repo/pulls/'
      path: '/pulls'
      fullPath: '/$username/$repo/pulls/'
      preLoaderRoute: typeof MainUsernameRepoPullsIndexRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/projects/': {
      id: '/_main/$username/$repo/projects/'
      path: '/projects'
      fullPath: '/$username/$repo/projects/'
      preLoaderRoute: typeof MainUsernameRepoProjectsIndexRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/issues/': {
      id: '/_main/$username/$repo/issues/'
      path: '/issues'
      fullPath: '/$username/$repo/issues/'
      preLoaderRoute: typeof MainUsernameRepoIssuesIndexRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/discussions/': {
      id: '/_main/$username/$repo/discussions/'
      path: '/discussions'
      fullPath: '/$username/$repo/discussions/'
      preLoaderRoute: typeof MainUsernameRepoDiscussionsIndexRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/tree/$': {
      id: '/_main/$username/$repo/tree/$'
      path: '/tree/$'
      fullPath: '/$username/$repo/tree/$'
      preLoaderRoute: typeof MainUsernameRepoTreeSplatRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/pulls/new': {
      id: '/_main/$username/$repo/pulls/new'
      path: '/pulls/new'
      fullPath: '/$username/$repo/pulls/new'
      preLoaderRoute: typeof MainUsernameRepoPullsNewRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/pulls/$number': {
      id: '/_main/$username/$repo/pulls/$number'
      path: '/pulls/$number'
      fullPath: '/$username/$repo/pulls/$number'
      preLoaderRoute: typeof MainUsernameRepoPullsNumberRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/projects/$projectId': {
      id: '/_main/$username/$repo/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/$username/$repo/projects/$projectId'
      preLoaderRoute: typeof MainUsernameRepoProjectsProjectIdRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/issues/new': {
      id: '/_main/$username/$repo/issues/new'
      path: '/issues/new'
      fullPath: '/$username/$repo/issues/new'
      preLoaderRoute: typeof MainUsernameRepoIssuesNewRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/issues/$number': {
      id: '/_main/$username/$repo/issues/$number'
      path: '/issues/$number'
      fullPath: '/$username/$repo/issues/$number'
      preLoaderRoute: typeof MainUsernameRepoIssuesNumberRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/discussions/new': {
      id: '/_main/$username/$repo/discussions/new'
      path: '/discussions/new'
      fullPath: '/$username/$repo/discussions/new'
      preLoaderRoute: typeof MainUsernameRepoDiscussionsNewRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/discussions/$number': {
      id: '/_main/$username/$repo/discussions/$number'
      path: '/discussions/$number'
      fullPath: '/$username/$repo/discussions/$number'
      preLoaderRoute: typeof MainUsernameRepoDiscussionsNumberRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/commits/$branch': {
      id: '/_main/$username/$repo/commits/$branch'
      path: '/$branch'
      fullPath: '/$username/$repo/commits/$branch'
      preLoaderRoute: typeof MainUsernameRepoCommitsBranchRouteImport
      parentRoute: typeof MainUsernameRepoCommitsRoute
    }
    '/_main/$username/$repo/blob/$': {
      id: '/_main/$username/$repo/blob/$'
      path: '/blob/$'
      fullPath: '/$username/$repo/blob/$'
      preLoaderRoute: typeof MainUsernameRepoBlobSplatRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/commits/$branch/': {
      id: '/_main/$username/$repo/commits/$branch/'
      path: '/'
      fullPath: '/$username/$repo/commits/$branch/'
      preLoaderRoute: typeof MainUsernameRepoCommitsBranchIndexRouteImport
      parentRoute: typeof MainUsernameRepoCommitsBranchRoute
    }
    '/_main/$username/$repo/commits/$branch/$oid': {
      id: '/_main/$username/$repo/commits/$branch/$oid'
      path: '/$oid'
      fullPath: '/$username/$repo/commits/$branch/$oid'
      preLoaderRoute: typeof MainUsernameRepoCommitsBranchOidRouteImport
      parentRoute: typeof MainUsernameRepoCommitsBranchRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainUsernameRepoCommitsBranchRouteChildren {
  MainUsernameRepoCommitsBranchOidRoute: typeof MainUsernameRepoCommitsBranchOidRoute
  MainUsernameRepoCommitsBranchIndexRoute: typeof MainUsernameRepoCommitsBranchIndexRoute
}

const MainUsernameRepoCommitsBranchRouteChildren: MainUsernameRepoCommitsBranchRouteChildren =
  {
    MainUsernameRepoCommitsBranchOidRoute:
      MainUsernameRepoCommitsBranchOidRoute,
    MainUsernameRepoCommitsBranchIndexRoute:
      MainUsernameRepoCommitsBranchIndexRoute,
  }

const MainUsernameRepoCommitsBranchRouteWithChildren =
  MainUsernameRepoCommitsBranchRoute._addFileChildren(
    MainUsernameRepoCommitsBranchRouteChildren,
  )

interface MainUsernameRepoCommitsRouteChildren {
  MainUsernameRepoCommitsBranchRoute: typeof MainUsernameRepoCommitsBranchRouteWithChildren
}

const MainUsernameRepoCommitsRouteChildren: MainUsernameRepoCommitsRouteChildren =
  {
    MainUsernameRepoCommitsBranchRoute:
      MainUsernameRepoCommitsBranchRouteWithChildren,
  }

const MainUsernameRepoCommitsRouteWithChildren =
  MainUsernameRepoCommitsRoute._addFileChildren(
    MainUsernameRepoCommitsRouteChildren,
  )

interface MainUsernameRepoRouteChildren {
  MainUsernameRepoCommitsRoute: typeof MainUsernameRepoCommitsRouteWithChildren
  MainUsernameRepoLabelsRoute: typeof MainUsernameRepoLabelsRoute
  MainUsernameRepoSettingsRoute: typeof MainUsernameRepoSettingsRoute
  MainUsernameRepoIndexRoute: typeof MainUsernameRepoIndexRoute
  MainUsernameRepoBlobSplatRoute: typeof MainUsernameRepoBlobSplatRoute
  MainUsernameRepoDiscussionsNumberRoute: typeof MainUsernameRepoDiscussionsNumberRoute
  MainUsernameRepoDiscussionsNewRoute: typeof MainUsernameRepoDiscussionsNewRoute
  MainUsernameRepoIssuesNumberRoute: typeof MainUsernameRepoIssuesNumberRoute
  MainUsernameRepoIssuesNewRoute: typeof MainUsernameRepoIssuesNewRoute
  MainUsernameRepoProjectsProjectIdRoute: typeof MainUsernameRepoProjectsProjectIdRoute
  MainUsernameRepoPullsNumberRoute: typeof MainUsernameRepoPullsNumberRoute
  MainUsernameRepoPullsNewRoute: typeof MainUsernameRepoPullsNewRoute
  MainUsernameRepoTreeSplatRoute: typeof MainUsernameRepoTreeSplatRoute
  MainUsernameRepoDiscussionsIndexRoute: typeof MainUsernameRepoDiscussionsIndexRoute
  MainUsernameRepoIssuesIndexRoute: typeof MainUsernameRepoIssuesIndexRoute
  MainUsernameRepoProjectsIndexRoute: typeof MainUsernameRepoProjectsIndexRoute
  MainUsernameRepoPullsIndexRoute: typeof MainUsernameRepoPullsIndexRoute
}

const MainUsernameRepoRouteChildren: MainUsernameRepoRouteChildren = {
  MainUsernameRepoCommitsRoute: MainUsernameRepoCommitsRouteWithChildren,
  MainUsernameRepoLabelsRoute: MainUsernameRepoLabelsRoute,
  MainUsernameRepoSettingsRoute: MainUsernameRepoSettingsRoute,
  MainUsernameRepoIndexRoute: MainUsernameRepoIndexRoute,
  MainUsernameRepoBlobSplatRoute: MainUsernameRepoBlobSplatRoute,
  MainUsernameRepoDiscussionsNumberRoute:
    MainUsernameRepoDiscussionsNumberRoute,
  MainUsernameRepoDiscussionsNewRoute: MainUsernameRepoDiscussionsNewRoute,
  MainUsernameRepoIssuesNumberRoute: MainUsernameRepoIssuesNumberRoute,
  MainUsernameRepoIssuesNewRoute: MainUsernameRepoIssuesNewRoute,
  MainUsernameRepoProjectsProjectIdRoute:
    MainUsernameRepoProjectsProjectIdRoute,
  MainUsernameRepoPullsNumberRoute: MainUsernameRepoPullsNumberRoute,
  MainUsernameRepoPullsNewRoute: MainUsernameRepoPullsNewRoute,
  MainUsernameRepoTreeSplatRoute: MainUsernameRepoTreeSplatRoute,
  MainUsernameRepoDiscussionsIndexRoute: MainUsernameRepoDiscussionsIndexRoute,
  MainUsernameRepoIssuesIndexRoute: MainUsernameRepoIssuesIndexRoute,
  MainUsernameRepoProjectsIndexRoute: MainUsernameRepoProjectsIndexRoute,
  MainUsernameRepoPullsIndexRoute: MainUsernameRepoPullsIndexRoute,
}

const MainUsernameRepoRouteWithChildren =
  MainUsernameRepoRoute._addFileChildren(MainUsernameRepoRouteChildren)

interface MainUsernameRouteChildren {
  MainUsernameRepoRoute: typeof MainUsernameRepoRouteWithChildren
  MainUsernameIndexRoute: typeof MainUsernameIndexRoute
}

const MainUsernameRouteChildren: MainUsernameRouteChildren = {
  MainUsernameRepoRoute: MainUsernameRepoRouteWithChildren,
  MainUsernameIndexRoute: MainUsernameIndexRoute,
}

const MainUsernameRouteWithChildren = MainUsernameRoute._addFileChildren(
  MainUsernameRouteChildren,
)

interface MainRouteChildren {
  MainUsernameRoute: typeof MainUsernameRouteWithChildren
  MainExploreRoute: typeof MainExploreRoute
  MainSearchRoute: typeof MainSearchRoute
  MainSettingsRoute: typeof MainSettingsRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainUsernameRoute: MainUsernameRouteWithChildren,
  MainExploreRoute: MainExploreRoute,
  MainSearchRoute: MainSearchRoute,
  MainSettingsRoute: MainSettingsRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
