/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SitemapRouteImport } from './app/sitemap'
import { Route as RateLimitedRouteImport } from './app/rate-limited'
import { Route as MainRouteImport } from './app/_main'
import { Route as AuthRouteImport } from './app/_auth'
import { Route as SplatRouteImport } from './app/$'
import { Route as MainIndexRouteImport } from './app/_main/index'
import { Route as MainTermsRouteImport } from './app/_main/terms'
import { Route as MainSettingsRouteImport } from './app/_main/settings'
import { Route as MainSecurityRouteImport } from './app/_main/security'
import { Route as MainSearchRouteImport } from './app/_main/search'
import { Route as MainPrivacyRouteImport } from './app/_main/privacy'
import { Route as MainFeaturesRouteImport } from './app/_main/features'
import { Route as MainExploreRouteImport } from './app/_main/explore'
import { Route as MainContactRouteImport } from './app/_main/contact'
import { Route as MainCareersRouteImport } from './app/_main/careers'
import { Route as MainAdminRouteImport } from './app/_main/admin'
import { Route as MainAboutRouteImport } from './app/_main/about'
import { Route as MainUsernameRouteImport } from './app/_main/$username'
import { Route as AuthVerifyEmailRouteImport } from './app/_auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './app/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './app/_auth/register'
import { Route as AuthLoginRouteImport } from './app/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './app/_auth/forgot-password'
import { Route as MainGistsIndexRouteImport } from './app/_main/gists/index'
import { Route as MainAdminIndexRouteImport } from './app/_main/admin/index'
import { Route as MainUsernameIndexRouteImport } from './app/_main/$username/index'
import { Route as MainSettingsMigrationsRouteImport } from './app/_main/settings/migrations'
import { Route as MainOrganizationsNewRouteImport } from './app/_main/organizations/new'
import { Route as MainGistsNewRouteImport } from './app/_main/gists/new'
import { Route as MainGistsIdRouteImport } from './app/_main/gists/$id'
import { Route as MainUsernameIndexOrgRouteImport } from './app/_main/$username/index-org'
import { Route as MainUsernameRepoRouteImport } from './app/_main/$username/$repo'
import { Route as MainNewImportIndexRouteImport } from './app/_main/new/import/index'
import { Route as MainAdminUtilsIndexRouteImport } from './app/_main/admin/utils/index'
import { Route as MainAdminUsersIndexRouteImport } from './app/_main/admin/users/index'
import { Route as MainAdminStatsIndexRouteImport } from './app/_main/admin/stats/index'
import { Route as MainAdminSettingsIndexRouteImport } from './app/_main/admin/settings/index'
import { Route as MainAdminRunnersIndexRouteImport } from './app/_main/admin/runners/index'
import { Route as MainAdminRepositoriesIndexRouteImport } from './app/_main/admin/repositories/index'
import { Route as MainAdminReportsIndexRouteImport } from './app/_main/admin/reports/index'
import { Route as MainAdminOrganizationsIndexRouteImport } from './app/_main/admin/organizations/index'
import { Route as MainAdminGistsIndexRouteImport } from './app/_main/admin/gists/index'
import { Route as MainAdminDmcaIndexRouteImport } from './app/_main/admin/dmca/index'
import { Route as MainAdminAuditLogsIndexRouteImport } from './app/_main/admin/audit-logs/index'
import { Route as MainAdminApplicationsIndexRouteImport } from './app/_main/admin/applications/index'
import { Route as MainUsernameRepoIndexRouteImport } from './app/_main/$username/$repo/index'
import { Route as MainGistsIdEditRouteImport } from './app/_main/gists/$id/edit'
import { Route as MainAdminUsersUserIdRouteImport } from './app/_main/admin/users/$userId'
import { Route as MainUsernameRepoSettingsRouteImport } from './app/_main/$username/$repo/settings'
import { Route as MainUsernameRepoLabelsRouteImport } from './app/_main/$username/$repo/labels'
import { Route as MainUsernameRepoCommitsRouteImport } from './app/_main/$username/$repo/commits'
import { Route as MainUsernameRepoWorkflowsIndexRouteImport } from './app/_main/$username/$repo/workflows/index'
import { Route as MainUsernameRepoRunsIndexRouteImport } from './app/_main/$username/$repo/runs/index'
import { Route as MainUsernameRepoReleasesIndexRouteImport } from './app/_main/$username/$repo/releases/index'
import { Route as MainUsernameRepoPullsIndexRouteImport } from './app/_main/$username/$repo/pulls/index'
import { Route as MainUsernameRepoProjectsIndexRouteImport } from './app/_main/$username/$repo/projects/index'
import { Route as MainUsernameRepoIssuesIndexRouteImport } from './app/_main/$username/$repo/issues/index'
import { Route as MainUsernameRepoDiscussionsIndexRouteImport } from './app/_main/$username/$repo/discussions/index'
import { Route as MainUsernameRepoTreeSplatRouteImport } from './app/_main/$username/$repo/tree/$'
import { Route as MainUsernameRepoRunsRunIdRouteImport } from './app/_main/$username/$repo/runs/$runId'
import { Route as MainUsernameRepoReleasesNewRouteImport } from './app/_main/$username/$repo/releases/new'
import { Route as MainUsernameRepoPullsNewRouteImport } from './app/_main/$username/$repo/pulls/new'
import { Route as MainUsernameRepoPullsNumberRouteImport } from './app/_main/$username/$repo/pulls/$number'
import { Route as MainUsernameRepoProjectsProjectIdRouteImport } from './app/_main/$username/$repo/projects/$projectId'
import { Route as MainUsernameRepoIssuesNewRouteImport } from './app/_main/$username/$repo/issues/new'
import { Route as MainUsernameRepoIssuesNumberRouteImport } from './app/_main/$username/$repo/issues/$number'
import { Route as MainUsernameRepoDiscussionsNewRouteImport } from './app/_main/$username/$repo/discussions/new'
import { Route as MainUsernameRepoDiscussionsNumberRouteImport } from './app/_main/$username/$repo/discussions/$number'
import { Route as MainUsernameRepoCommitsBranchRouteImport } from './app/_main/$username/$repo/commits/$branch'
import { Route as MainUsernameRepoBlobSplatRouteImport } from './app/_main/$username/$repo/blob/$'
import { Route as MainUsernameRepoCommitsBranchIndexRouteImport } from './app/_main/$username/$repo/commits/$branch/index'
import { Route as MainUsernameRepoReleasesTagTagRouteImport } from './app/_main/$username/$repo/releases/tag/$tag'
import { Route as MainUsernameRepoReleasesIdEditRouteImport } from './app/_main/$username/$repo/releases/$id/edit'
import { Route as MainUsernameRepoCommitsBranchOidRouteImport } from './app/_main/$username/$repo/commits/$branch/$oid'

const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const RateLimitedRoute = RateLimitedRouteImport.update({
  id: '/rate-limited',
  path: '/rate-limited',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainTermsRoute = MainTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRoute,
} as any)
const MainSecurityRoute = MainSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => MainRoute,
} as any)
const MainSearchRoute = MainSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MainRoute,
} as any)
const MainPrivacyRoute = MainPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MainRoute,
} as any)
const MainFeaturesRoute = MainFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => MainRoute,
} as any)
const MainExploreRoute = MainExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => MainRoute,
} as any)
const MainContactRoute = MainContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MainRoute,
} as any)
const MainCareersRoute = MainCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => MainRoute,
} as any)
const MainAdminRoute = MainAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => MainRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRoute,
} as any)
const MainUsernameRoute = MainUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => MainRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const MainGistsIndexRoute = MainGistsIndexRouteImport.update({
  id: '/gists/',
  path: '/gists/',
  getParentRoute: () => MainRoute,
} as any)
const MainAdminIndexRoute = MainAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainUsernameIndexRoute = MainUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainUsernameRoute,
} as any)
const MainSettingsMigrationsRoute = MainSettingsMigrationsRouteImport.update({
  id: '/migrations',
  path: '/migrations',
  getParentRoute: () => MainSettingsRoute,
} as any)
const MainOrganizationsNewRoute = MainOrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => MainRoute,
} as any)
const MainGistsNewRoute = MainGistsNewRouteImport.update({
  id: '/gists/new',
  path: '/gists/new',
  getParentRoute: () => MainRoute,
} as any)
const MainGistsIdRoute = MainGistsIdRouteImport.update({
  id: '/gists/$id',
  path: '/gists/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainUsernameIndexOrgRoute = MainUsernameIndexOrgRouteImport.update({
  id: '/index-org',
  path: '/index-org',
  getParentRoute: () => MainUsernameRoute,
} as any)
const MainUsernameRepoRoute = MainUsernameRepoRouteImport.update({
  id: '/$repo',
  path: '/$repo',
  getParentRoute: () => MainUsernameRoute,
} as any)
const MainNewImportIndexRoute = MainNewImportIndexRouteImport.update({
  id: '/new/import/',
  path: '/new/import/',
  getParentRoute: () => MainRoute,
} as any)
const MainAdminUtilsIndexRoute = MainAdminUtilsIndexRouteImport.update({
  id: '/utils/',
  path: '/utils/',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminUsersIndexRoute = MainAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminStatsIndexRoute = MainAdminStatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminSettingsIndexRoute = MainAdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminRunnersIndexRoute = MainAdminRunnersIndexRouteImport.update({
  id: '/runners/',
  path: '/runners/',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminRepositoriesIndexRoute =
  MainAdminRepositoriesIndexRouteImport.update({
    id: '/repositories/',
    path: '/repositories/',
    getParentRoute: () => MainAdminRoute,
  } as any)
const MainAdminReportsIndexRoute = MainAdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminOrganizationsIndexRoute =
  MainAdminOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => MainAdminRoute,
  } as any)
const MainAdminGistsIndexRoute = MainAdminGistsIndexRouteImport.update({
  id: '/gists/',
  path: '/gists/',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminDmcaIndexRoute = MainAdminDmcaIndexRouteImport.update({
  id: '/dmca/',
  path: '/dmca/',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminAuditLogsIndexRoute = MainAdminAuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminApplicationsIndexRoute =
  MainAdminApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => MainAdminRoute,
  } as any)
const MainUsernameRepoIndexRoute = MainUsernameRepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainUsernameRepoRoute,
} as any)
const MainGistsIdEditRoute = MainGistsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MainGistsIdRoute,
} as any)
const MainAdminUsersUserIdRoute = MainAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainUsernameRepoSettingsRoute =
  MainUsernameRepoSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoLabelsRoute = MainUsernameRepoLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => MainUsernameRepoRoute,
} as any)
const MainUsernameRepoCommitsRoute = MainUsernameRepoCommitsRouteImport.update({
  id: '/commits',
  path: '/commits',
  getParentRoute: () => MainUsernameRepoRoute,
} as any)
const MainUsernameRepoWorkflowsIndexRoute =
  MainUsernameRepoWorkflowsIndexRouteImport.update({
    id: '/workflows/',
    path: '/workflows/',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoRunsIndexRoute =
  MainUsernameRepoRunsIndexRouteImport.update({
    id: '/runs/',
    path: '/runs/',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoReleasesIndexRoute =
  MainUsernameRepoReleasesIndexRouteImport.update({
    id: '/releases/',
    path: '/releases/',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoPullsIndexRoute =
  MainUsernameRepoPullsIndexRouteImport.update({
    id: '/pulls/',
    path: '/pulls/',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoProjectsIndexRoute =
  MainUsernameRepoProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoIssuesIndexRoute =
  MainUsernameRepoIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoDiscussionsIndexRoute =
  MainUsernameRepoDiscussionsIndexRouteImport.update({
    id: '/discussions/',
    path: '/discussions/',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoTreeSplatRoute =
  MainUsernameRepoTreeSplatRouteImport.update({
    id: '/tree/$',
    path: '/tree/$',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoRunsRunIdRoute =
  MainUsernameRepoRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoReleasesNewRoute =
  MainUsernameRepoReleasesNewRouteImport.update({
    id: '/releases/new',
    path: '/releases/new',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoPullsNewRoute =
  MainUsernameRepoPullsNewRouteImport.update({
    id: '/pulls/new',
    path: '/pulls/new',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoPullsNumberRoute =
  MainUsernameRepoPullsNumberRouteImport.update({
    id: '/pulls/$number',
    path: '/pulls/$number',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoProjectsProjectIdRoute =
  MainUsernameRepoProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoIssuesNewRoute =
  MainUsernameRepoIssuesNewRouteImport.update({
    id: '/issues/new',
    path: '/issues/new',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoIssuesNumberRoute =
  MainUsernameRepoIssuesNumberRouteImport.update({
    id: '/issues/$number',
    path: '/issues/$number',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoDiscussionsNewRoute =
  MainUsernameRepoDiscussionsNewRouteImport.update({
    id: '/discussions/new',
    path: '/discussions/new',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoDiscussionsNumberRoute =
  MainUsernameRepoDiscussionsNumberRouteImport.update({
    id: '/discussions/$number',
    path: '/discussions/$number',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoCommitsBranchRoute =
  MainUsernameRepoCommitsBranchRouteImport.update({
    id: '/$branch',
    path: '/$branch',
    getParentRoute: () => MainUsernameRepoCommitsRoute,
  } as any)
const MainUsernameRepoBlobSplatRoute =
  MainUsernameRepoBlobSplatRouteImport.update({
    id: '/blob/$',
    path: '/blob/$',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoCommitsBranchIndexRoute =
  MainUsernameRepoCommitsBranchIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainUsernameRepoCommitsBranchRoute,
  } as any)
const MainUsernameRepoReleasesTagTagRoute =
  MainUsernameRepoReleasesTagTagRouteImport.update({
    id: '/releases/tag/$tag',
    path: '/releases/tag/$tag',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoReleasesIdEditRoute =
  MainUsernameRepoReleasesIdEditRouteImport.update({
    id: '/releases/$id/edit',
    path: '/releases/$id/edit',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoCommitsBranchOidRoute =
  MainUsernameRepoCommitsBranchOidRouteImport.update({
    id: '/$oid',
    path: '/$oid',
    getParentRoute: () => MainUsernameRepoCommitsBranchRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof MainIndexRoute
  '/rate-limited': typeof RateLimitedRoute
  '/sitemap': typeof SitemapRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/$username': typeof MainUsernameRouteWithChildren
  '/about': typeof MainAboutRoute
  '/admin': typeof MainAdminRouteWithChildren
  '/careers': typeof MainCareersRoute
  '/contact': typeof MainContactRoute
  '/explore': typeof MainExploreRoute
  '/features': typeof MainFeaturesRoute
  '/privacy': typeof MainPrivacyRoute
  '/search': typeof MainSearchRoute
  '/security': typeof MainSecurityRoute
  '/settings': typeof MainSettingsRouteWithChildren
  '/terms': typeof MainTermsRoute
  '/$username/$repo': typeof MainUsernameRepoRouteWithChildren
  '/$username/index-org': typeof MainUsernameIndexOrgRoute
  '/gists/$id': typeof MainGistsIdRouteWithChildren
  '/gists/new': typeof MainGistsNewRoute
  '/organizations/new': typeof MainOrganizationsNewRoute
  '/settings/migrations': typeof MainSettingsMigrationsRoute
  '/$username/': typeof MainUsernameIndexRoute
  '/admin/': typeof MainAdminIndexRoute
  '/gists/': typeof MainGistsIndexRoute
  '/$username/$repo/commits': typeof MainUsernameRepoCommitsRouteWithChildren
  '/$username/$repo/labels': typeof MainUsernameRepoLabelsRoute
  '/$username/$repo/settings': typeof MainUsernameRepoSettingsRoute
  '/admin/users/$userId': typeof MainAdminUsersUserIdRoute
  '/gists/$id/edit': typeof MainGistsIdEditRoute
  '/$username/$repo/': typeof MainUsernameRepoIndexRoute
  '/admin/applications/': typeof MainAdminApplicationsIndexRoute
  '/admin/audit-logs/': typeof MainAdminAuditLogsIndexRoute
  '/admin/dmca/': typeof MainAdminDmcaIndexRoute
  '/admin/gists/': typeof MainAdminGistsIndexRoute
  '/admin/organizations/': typeof MainAdminOrganizationsIndexRoute
  '/admin/reports/': typeof MainAdminReportsIndexRoute
  '/admin/repositories/': typeof MainAdminRepositoriesIndexRoute
  '/admin/runners/': typeof MainAdminRunnersIndexRoute
  '/admin/settings/': typeof MainAdminSettingsIndexRoute
  '/admin/stats/': typeof MainAdminStatsIndexRoute
  '/admin/users/': typeof MainAdminUsersIndexRoute
  '/admin/utils/': typeof MainAdminUtilsIndexRoute
  '/new/import/': typeof MainNewImportIndexRoute
  '/$username/$repo/blob/$': typeof MainUsernameRepoBlobSplatRoute
  '/$username/$repo/commits/$branch': typeof MainUsernameRepoCommitsBranchRouteWithChildren
  '/$username/$repo/discussions/$number': typeof MainUsernameRepoDiscussionsNumberRoute
  '/$username/$repo/discussions/new': typeof MainUsernameRepoDiscussionsNewRoute
  '/$username/$repo/issues/$number': typeof MainUsernameRepoIssuesNumberRoute
  '/$username/$repo/issues/new': typeof MainUsernameRepoIssuesNewRoute
  '/$username/$repo/projects/$projectId': typeof MainUsernameRepoProjectsProjectIdRoute
  '/$username/$repo/pulls/$number': typeof MainUsernameRepoPullsNumberRoute
  '/$username/$repo/pulls/new': typeof MainUsernameRepoPullsNewRoute
  '/$username/$repo/releases/new': typeof MainUsernameRepoReleasesNewRoute
  '/$username/$repo/runs/$runId': typeof MainUsernameRepoRunsRunIdRoute
  '/$username/$repo/tree/$': typeof MainUsernameRepoTreeSplatRoute
  '/$username/$repo/discussions/': typeof MainUsernameRepoDiscussionsIndexRoute
  '/$username/$repo/issues/': typeof MainUsernameRepoIssuesIndexRoute
  '/$username/$repo/projects/': typeof MainUsernameRepoProjectsIndexRoute
  '/$username/$repo/pulls/': typeof MainUsernameRepoPullsIndexRoute
  '/$username/$repo/releases/': typeof MainUsernameRepoReleasesIndexRoute
  '/$username/$repo/runs/': typeof MainUsernameRepoRunsIndexRoute
  '/$username/$repo/workflows/': typeof MainUsernameRepoWorkflowsIndexRoute
  '/$username/$repo/commits/$branch/$oid': typeof MainUsernameRepoCommitsBranchOidRoute
  '/$username/$repo/releases/$id/edit': typeof MainUsernameRepoReleasesIdEditRoute
  '/$username/$repo/releases/tag/$tag': typeof MainUsernameRepoReleasesTagTagRoute
  '/$username/$repo/commits/$branch/': typeof MainUsernameRepoCommitsBranchIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof MainIndexRoute
  '/rate-limited': typeof RateLimitedRoute
  '/sitemap': typeof SitemapRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/about': typeof MainAboutRoute
  '/careers': typeof MainCareersRoute
  '/contact': typeof MainContactRoute
  '/explore': typeof MainExploreRoute
  '/features': typeof MainFeaturesRoute
  '/privacy': typeof MainPrivacyRoute
  '/search': typeof MainSearchRoute
  '/security': typeof MainSecurityRoute
  '/settings': typeof MainSettingsRouteWithChildren
  '/terms': typeof MainTermsRoute
  '/$username/index-org': typeof MainUsernameIndexOrgRoute
  '/gists/$id': typeof MainGistsIdRouteWithChildren
  '/gists/new': typeof MainGistsNewRoute
  '/organizations/new': typeof MainOrganizationsNewRoute
  '/settings/migrations': typeof MainSettingsMigrationsRoute
  '/$username': typeof MainUsernameIndexRoute
  '/admin': typeof MainAdminIndexRoute
  '/gists': typeof MainGistsIndexRoute
  '/$username/$repo/commits': typeof MainUsernameRepoCommitsRouteWithChildren
  '/$username/$repo/labels': typeof MainUsernameRepoLabelsRoute
  '/$username/$repo/settings': typeof MainUsernameRepoSettingsRoute
  '/admin/users/$userId': typeof MainAdminUsersUserIdRoute
  '/gists/$id/edit': typeof MainGistsIdEditRoute
  '/$username/$repo': typeof MainUsernameRepoIndexRoute
  '/admin/applications': typeof MainAdminApplicationsIndexRoute
  '/admin/audit-logs': typeof MainAdminAuditLogsIndexRoute
  '/admin/dmca': typeof MainAdminDmcaIndexRoute
  '/admin/gists': typeof MainAdminGistsIndexRoute
  '/admin/organizations': typeof MainAdminOrganizationsIndexRoute
  '/admin/reports': typeof MainAdminReportsIndexRoute
  '/admin/repositories': typeof MainAdminRepositoriesIndexRoute
  '/admin/runners': typeof MainAdminRunnersIndexRoute
  '/admin/settings': typeof MainAdminSettingsIndexRoute
  '/admin/stats': typeof MainAdminStatsIndexRoute
  '/admin/users': typeof MainAdminUsersIndexRoute
  '/admin/utils': typeof MainAdminUtilsIndexRoute
  '/new/import': typeof MainNewImportIndexRoute
  '/$username/$repo/blob/$': typeof MainUsernameRepoBlobSplatRoute
  '/$username/$repo/discussions/$number': typeof MainUsernameRepoDiscussionsNumberRoute
  '/$username/$repo/discussions/new': typeof MainUsernameRepoDiscussionsNewRoute
  '/$username/$repo/issues/$number': typeof MainUsernameRepoIssuesNumberRoute
  '/$username/$repo/issues/new': typeof MainUsernameRepoIssuesNewRoute
  '/$username/$repo/projects/$projectId': typeof MainUsernameRepoProjectsProjectIdRoute
  '/$username/$repo/pulls/$number': typeof MainUsernameRepoPullsNumberRoute
  '/$username/$repo/pulls/new': typeof MainUsernameRepoPullsNewRoute
  '/$username/$repo/releases/new': typeof MainUsernameRepoReleasesNewRoute
  '/$username/$repo/runs/$runId': typeof MainUsernameRepoRunsRunIdRoute
  '/$username/$repo/tree/$': typeof MainUsernameRepoTreeSplatRoute
  '/$username/$repo/discussions': typeof MainUsernameRepoDiscussionsIndexRoute
  '/$username/$repo/issues': typeof MainUsernameRepoIssuesIndexRoute
  '/$username/$repo/projects': typeof MainUsernameRepoProjectsIndexRoute
  '/$username/$repo/pulls': typeof MainUsernameRepoPullsIndexRoute
  '/$username/$repo/releases': typeof MainUsernameRepoReleasesIndexRoute
  '/$username/$repo/runs': typeof MainUsernameRepoRunsIndexRoute
  '/$username/$repo/workflows': typeof MainUsernameRepoWorkflowsIndexRoute
  '/$username/$repo/commits/$branch/$oid': typeof MainUsernameRepoCommitsBranchOidRoute
  '/$username/$repo/releases/$id/edit': typeof MainUsernameRepoReleasesIdEditRoute
  '/$username/$repo/releases/tag/$tag': typeof MainUsernameRepoReleasesTagTagRoute
  '/$username/$repo/commits/$branch': typeof MainUsernameRepoCommitsBranchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/rate-limited': typeof RateLimitedRoute
  '/sitemap': typeof SitemapRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_main/$username': typeof MainUsernameRouteWithChildren
  '/_main/about': typeof MainAboutRoute
  '/_main/admin': typeof MainAdminRouteWithChildren
  '/_main/careers': typeof MainCareersRoute
  '/_main/contact': typeof MainContactRoute
  '/_main/explore': typeof MainExploreRoute
  '/_main/features': typeof MainFeaturesRoute
  '/_main/privacy': typeof MainPrivacyRoute
  '/_main/search': typeof MainSearchRoute
  '/_main/security': typeof MainSecurityRoute
  '/_main/settings': typeof MainSettingsRouteWithChildren
  '/_main/terms': typeof MainTermsRoute
  '/_main/': typeof MainIndexRoute
  '/_main/$username/$repo': typeof MainUsernameRepoRouteWithChildren
  '/_main/$username/index-org': typeof MainUsernameIndexOrgRoute
  '/_main/gists/$id': typeof MainGistsIdRouteWithChildren
  '/_main/gists/new': typeof MainGistsNewRoute
  '/_main/organizations/new': typeof MainOrganizationsNewRoute
  '/_main/settings/migrations': typeof MainSettingsMigrationsRoute
  '/_main/$username/': typeof MainUsernameIndexRoute
  '/_main/admin/': typeof MainAdminIndexRoute
  '/_main/gists/': typeof MainGistsIndexRoute
  '/_main/$username/$repo/commits': typeof MainUsernameRepoCommitsRouteWithChildren
  '/_main/$username/$repo/labels': typeof MainUsernameRepoLabelsRoute
  '/_main/$username/$repo/settings': typeof MainUsernameRepoSettingsRoute
  '/_main/admin/users/$userId': typeof MainAdminUsersUserIdRoute
  '/_main/gists/$id/edit': typeof MainGistsIdEditRoute
  '/_main/$username/$repo/': typeof MainUsernameRepoIndexRoute
  '/_main/admin/applications/': typeof MainAdminApplicationsIndexRoute
  '/_main/admin/audit-logs/': typeof MainAdminAuditLogsIndexRoute
  '/_main/admin/dmca/': typeof MainAdminDmcaIndexRoute
  '/_main/admin/gists/': typeof MainAdminGistsIndexRoute
  '/_main/admin/organizations/': typeof MainAdminOrganizationsIndexRoute
  '/_main/admin/reports/': typeof MainAdminReportsIndexRoute
  '/_main/admin/repositories/': typeof MainAdminRepositoriesIndexRoute
  '/_main/admin/runners/': typeof MainAdminRunnersIndexRoute
  '/_main/admin/settings/': typeof MainAdminSettingsIndexRoute
  '/_main/admin/stats/': typeof MainAdminStatsIndexRoute
  '/_main/admin/users/': typeof MainAdminUsersIndexRoute
  '/_main/admin/utils/': typeof MainAdminUtilsIndexRoute
  '/_main/new/import/': typeof MainNewImportIndexRoute
  '/_main/$username/$repo/blob/$': typeof MainUsernameRepoBlobSplatRoute
  '/_main/$username/$repo/commits/$branch': typeof MainUsernameRepoCommitsBranchRouteWithChildren
  '/_main/$username/$repo/discussions/$number': typeof MainUsernameRepoDiscussionsNumberRoute
  '/_main/$username/$repo/discussions/new': typeof MainUsernameRepoDiscussionsNewRoute
  '/_main/$username/$repo/issues/$number': typeof MainUsernameRepoIssuesNumberRoute
  '/_main/$username/$repo/issues/new': typeof MainUsernameRepoIssuesNewRoute
  '/_main/$username/$repo/projects/$projectId': typeof MainUsernameRepoProjectsProjectIdRoute
  '/_main/$username/$repo/pulls/$number': typeof MainUsernameRepoPullsNumberRoute
  '/_main/$username/$repo/pulls/new': typeof MainUsernameRepoPullsNewRoute
  '/_main/$username/$repo/releases/new': typeof MainUsernameRepoReleasesNewRoute
  '/_main/$username/$repo/runs/$runId': typeof MainUsernameRepoRunsRunIdRoute
  '/_main/$username/$repo/tree/$': typeof MainUsernameRepoTreeSplatRoute
  '/_main/$username/$repo/discussions/': typeof MainUsernameRepoDiscussionsIndexRoute
  '/_main/$username/$repo/issues/': typeof MainUsernameRepoIssuesIndexRoute
  '/_main/$username/$repo/projects/': typeof MainUsernameRepoProjectsIndexRoute
  '/_main/$username/$repo/pulls/': typeof MainUsernameRepoPullsIndexRoute
  '/_main/$username/$repo/releases/': typeof MainUsernameRepoReleasesIndexRoute
  '/_main/$username/$repo/runs/': typeof MainUsernameRepoRunsIndexRoute
  '/_main/$username/$repo/workflows/': typeof MainUsernameRepoWorkflowsIndexRoute
  '/_main/$username/$repo/commits/$branch/$oid': typeof MainUsernameRepoCommitsBranchOidRoute
  '/_main/$username/$repo/releases/$id/edit': typeof MainUsernameRepoReleasesIdEditRoute
  '/_main/$username/$repo/releases/tag/$tag': typeof MainUsernameRepoReleasesTagTagRoute
  '/_main/$username/$repo/commits/$branch/': typeof MainUsernameRepoCommitsBranchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/rate-limited'
    | '/sitemap'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/$username'
    | '/about'
    | '/admin'
    | '/careers'
    | '/contact'
    | '/explore'
    | '/features'
    | '/privacy'
    | '/search'
    | '/security'
    | '/settings'
    | '/terms'
    | '/$username/$repo'
    | '/$username/index-org'
    | '/gists/$id'
    | '/gists/new'
    | '/organizations/new'
    | '/settings/migrations'
    | '/$username/'
    | '/admin/'
    | '/gists/'
    | '/$username/$repo/commits'
    | '/$username/$repo/labels'
    | '/$username/$repo/settings'
    | '/admin/users/$userId'
    | '/gists/$id/edit'
    | '/$username/$repo/'
    | '/admin/applications/'
    | '/admin/audit-logs/'
    | '/admin/dmca/'
    | '/admin/gists/'
    | '/admin/organizations/'
    | '/admin/reports/'
    | '/admin/repositories/'
    | '/admin/runners/'
    | '/admin/settings/'
    | '/admin/stats/'
    | '/admin/users/'
    | '/admin/utils/'
    | '/new/import/'
    | '/$username/$repo/blob/$'
    | '/$username/$repo/commits/$branch'
    | '/$username/$repo/discussions/$number'
    | '/$username/$repo/discussions/new'
    | '/$username/$repo/issues/$number'
    | '/$username/$repo/issues/new'
    | '/$username/$repo/projects/$projectId'
    | '/$username/$repo/pulls/$number'
    | '/$username/$repo/pulls/new'
    | '/$username/$repo/releases/new'
    | '/$username/$repo/runs/$runId'
    | '/$username/$repo/tree/$'
    | '/$username/$repo/discussions/'
    | '/$username/$repo/issues/'
    | '/$username/$repo/projects/'
    | '/$username/$repo/pulls/'
    | '/$username/$repo/releases/'
    | '/$username/$repo/runs/'
    | '/$username/$repo/workflows/'
    | '/$username/$repo/commits/$branch/$oid'
    | '/$username/$repo/releases/$id/edit'
    | '/$username/$repo/releases/tag/$tag'
    | '/$username/$repo/commits/$branch/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/rate-limited'
    | '/sitemap'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/about'
    | '/careers'
    | '/contact'
    | '/explore'
    | '/features'
    | '/privacy'
    | '/search'
    | '/security'
    | '/settings'
    | '/terms'
    | '/$username/index-org'
    | '/gists/$id'
    | '/gists/new'
    | '/organizations/new'
    | '/settings/migrations'
    | '/$username'
    | '/admin'
    | '/gists'
    | '/$username/$repo/commits'
    | '/$username/$repo/labels'
    | '/$username/$repo/settings'
    | '/admin/users/$userId'
    | '/gists/$id/edit'
    | '/$username/$repo'
    | '/admin/applications'
    | '/admin/audit-logs'
    | '/admin/dmca'
    | '/admin/gists'
    | '/admin/organizations'
    | '/admin/reports'
    | '/admin/repositories'
    | '/admin/runners'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/users'
    | '/admin/utils'
    | '/new/import'
    | '/$username/$repo/blob/$'
    | '/$username/$repo/discussions/$number'
    | '/$username/$repo/discussions/new'
    | '/$username/$repo/issues/$number'
    | '/$username/$repo/issues/new'
    | '/$username/$repo/projects/$projectId'
    | '/$username/$repo/pulls/$number'
    | '/$username/$repo/pulls/new'
    | '/$username/$repo/releases/new'
    | '/$username/$repo/runs/$runId'
    | '/$username/$repo/tree/$'
    | '/$username/$repo/discussions'
    | '/$username/$repo/issues'
    | '/$username/$repo/projects'
    | '/$username/$repo/pulls'
    | '/$username/$repo/releases'
    | '/$username/$repo/runs'
    | '/$username/$repo/workflows'
    | '/$username/$repo/commits/$branch/$oid'
    | '/$username/$repo/releases/$id/edit'
    | '/$username/$repo/releases/tag/$tag'
    | '/$username/$repo/commits/$branch'
  id:
    | '__root__'
    | '/$'
    | '/_auth'
    | '/_main'
    | '/rate-limited'
    | '/sitemap'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/_main/$username'
    | '/_main/about'
    | '/_main/admin'
    | '/_main/careers'
    | '/_main/contact'
    | '/_main/explore'
    | '/_main/features'
    | '/_main/privacy'
    | '/_main/search'
    | '/_main/security'
    | '/_main/settings'
    | '/_main/terms'
    | '/_main/'
    | '/_main/$username/$repo'
    | '/_main/$username/index-org'
    | '/_main/gists/$id'
    | '/_main/gists/new'
    | '/_main/organizations/new'
    | '/_main/settings/migrations'
    | '/_main/$username/'
    | '/_main/admin/'
    | '/_main/gists/'
    | '/_main/$username/$repo/commits'
    | '/_main/$username/$repo/labels'
    | '/_main/$username/$repo/settings'
    | '/_main/admin/users/$userId'
    | '/_main/gists/$id/edit'
    | '/_main/$username/$repo/'
    | '/_main/admin/applications/'
    | '/_main/admin/audit-logs/'
    | '/_main/admin/dmca/'
    | '/_main/admin/gists/'
    | '/_main/admin/organizations/'
    | '/_main/admin/reports/'
    | '/_main/admin/repositories/'
    | '/_main/admin/runners/'
    | '/_main/admin/settings/'
    | '/_main/admin/stats/'
    | '/_main/admin/users/'
    | '/_main/admin/utils/'
    | '/_main/new/import/'
    | '/_main/$username/$repo/blob/$'
    | '/_main/$username/$repo/commits/$branch'
    | '/_main/$username/$repo/discussions/$number'
    | '/_main/$username/$repo/discussions/new'
    | '/_main/$username/$repo/issues/$number'
    | '/_main/$username/$repo/issues/new'
    | '/_main/$username/$repo/projects/$projectId'
    | '/_main/$username/$repo/pulls/$number'
    | '/_main/$username/$repo/pulls/new'
    | '/_main/$username/$repo/releases/new'
    | '/_main/$username/$repo/runs/$runId'
    | '/_main/$username/$repo/tree/$'
    | '/_main/$username/$repo/discussions/'
    | '/_main/$username/$repo/issues/'
    | '/_main/$username/$repo/projects/'
    | '/_main/$username/$repo/pulls/'
    | '/_main/$username/$repo/releases/'
    | '/_main/$username/$repo/runs/'
    | '/_main/$username/$repo/workflows/'
    | '/_main/$username/$repo/commits/$branch/$oid'
    | '/_main/$username/$repo/releases/$id/edit'
    | '/_main/$username/$repo/releases/tag/$tag'
    | '/_main/$username/$repo/commits/$branch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
  RateLimitedRoute: typeof RateLimitedRoute
  SitemapRoute: typeof SitemapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-limited': {
      id: '/rate-limited'
      path: '/rate-limited'
      fullPath: '/rate-limited'
      preLoaderRoute: typeof RateLimitedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/terms': {
      id: '/_main/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MainTermsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/security': {
      id: '/_main/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof MainSecurityRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/search': {
      id: '/_main/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof MainSearchRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/privacy': {
      id: '/_main/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MainPrivacyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/features': {
      id: '/_main/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof MainFeaturesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/explore': {
      id: '/_main/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof MainExploreRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/contact': {
      id: '/_main/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MainContactRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/careers': {
      id: '/_main/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof MainCareersRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/admin': {
      id: '/_main/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof MainAdminRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/$username': {
      id: '/_main/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof MainUsernameRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/gists/': {
      id: '/_main/gists/'
      path: '/gists'
      fullPath: '/gists/'
      preLoaderRoute: typeof MainGistsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/admin/': {
      id: '/_main/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof MainAdminIndexRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/$username/': {
      id: '/_main/$username/'
      path: '/'
      fullPath: '/$username/'
      preLoaderRoute: typeof MainUsernameIndexRouteImport
      parentRoute: typeof MainUsernameRoute
    }
    '/_main/settings/migrations': {
      id: '/_main/settings/migrations'
      path: '/migrations'
      fullPath: '/settings/migrations'
      preLoaderRoute: typeof MainSettingsMigrationsRouteImport
      parentRoute: typeof MainSettingsRoute
    }
    '/_main/organizations/new': {
      id: '/_main/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof MainOrganizationsNewRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/gists/new': {
      id: '/_main/gists/new'
      path: '/gists/new'
      fullPath: '/gists/new'
      preLoaderRoute: typeof MainGistsNewRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/gists/$id': {
      id: '/_main/gists/$id'
      path: '/gists/$id'
      fullPath: '/gists/$id'
      preLoaderRoute: typeof MainGistsIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/$username/index-org': {
      id: '/_main/$username/index-org'
      path: '/index-org'
      fullPath: '/$username/index-org'
      preLoaderRoute: typeof MainUsernameIndexOrgRouteImport
      parentRoute: typeof MainUsernameRoute
    }
    '/_main/$username/$repo': {
      id: '/_main/$username/$repo'
      path: '/$repo'
      fullPath: '/$username/$repo'
      preLoaderRoute: typeof MainUsernameRepoRouteImport
      parentRoute: typeof MainUsernameRoute
    }
    '/_main/new/import/': {
      id: '/_main/new/import/'
      path: '/new/import'
      fullPath: '/new/import/'
      preLoaderRoute: typeof MainNewImportIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/admin/utils/': {
      id: '/_main/admin/utils/'
      path: '/utils'
      fullPath: '/admin/utils/'
      preLoaderRoute: typeof MainAdminUtilsIndexRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/users/': {
      id: '/_main/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof MainAdminUsersIndexRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/stats/': {
      id: '/_main/admin/stats/'
      path: '/stats'
      fullPath: '/admin/stats/'
      preLoaderRoute: typeof MainAdminStatsIndexRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/settings/': {
      id: '/_main/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof MainAdminSettingsIndexRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/runners/': {
      id: '/_main/admin/runners/'
      path: '/runners'
      fullPath: '/admin/runners/'
      preLoaderRoute: typeof MainAdminRunnersIndexRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/repositories/': {
      id: '/_main/admin/repositories/'
      path: '/repositories'
      fullPath: '/admin/repositories/'
      preLoaderRoute: typeof MainAdminRepositoriesIndexRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/reports/': {
      id: '/_main/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof MainAdminReportsIndexRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/organizations/': {
      id: '/_main/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof MainAdminOrganizationsIndexRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/gists/': {
      id: '/_main/admin/gists/'
      path: '/gists'
      fullPath: '/admin/gists/'
      preLoaderRoute: typeof MainAdminGistsIndexRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/dmca/': {
      id: '/_main/admin/dmca/'
      path: '/dmca'
      fullPath: '/admin/dmca/'
      preLoaderRoute: typeof MainAdminDmcaIndexRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/audit-logs/': {
      id: '/_main/admin/audit-logs/'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs/'
      preLoaderRoute: typeof MainAdminAuditLogsIndexRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/applications/': {
      id: '/_main/admin/applications/'
      path: '/applications'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof MainAdminApplicationsIndexRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/$username/$repo/': {
      id: '/_main/$username/$repo/'
      path: '/'
      fullPath: '/$username/$repo/'
      preLoaderRoute: typeof MainUsernameRepoIndexRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/gists/$id/edit': {
      id: '/_main/gists/$id/edit'
      path: '/edit'
      fullPath: '/gists/$id/edit'
      preLoaderRoute: typeof MainGistsIdEditRouteImport
      parentRoute: typeof MainGistsIdRoute
    }
    '/_main/admin/users/$userId': {
      id: '/_main/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof MainAdminUsersUserIdRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/$username/$repo/settings': {
      id: '/_main/$username/$repo/settings'
      path: '/settings'
      fullPath: '/$username/$repo/settings'
      preLoaderRoute: typeof MainUsernameRepoSettingsRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/labels': {
      id: '/_main/$username/$repo/labels'
      path: '/labels'
      fullPath: '/$username/$repo/labels'
      preLoaderRoute: typeof MainUsernameRepoLabelsRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/commits': {
      id: '/_main/$username/$repo/commits'
      path: '/commits'
      fullPath: '/$username/$repo/commits'
      preLoaderRoute: typeof MainUsernameRepoCommitsRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/workflows/': {
      id: '/_main/$username/$repo/workflows/'
      path: '/workflows'
      fullPath: '/$username/$repo/workflows/'
      preLoaderRoute: typeof MainUsernameRepoWorkflowsIndexRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/runs/': {
      id: '/_main/$username/$repo/runs/'
      path: '/runs'
      fullPath: '/$username/$repo/runs/'
      preLoaderRoute: typeof MainUsernameRepoRunsIndexRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/releases/': {
      id: '/_main/$username/$repo/releases/'
      path: '/releases'
      fullPath: '/$username/$repo/releases/'
      preLoaderRoute: typeof MainUsernameRepoReleasesIndexRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/pulls/': {
      id: '/_main/$username/$repo/pulls/'
      path: '/pulls'
      fullPath: '/$username/$repo/pulls/'
      preLoaderRoute: typeof MainUsernameRepoPullsIndexRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/projects/': {
      id: '/_main/$username/$repo/projects/'
      path: '/projects'
      fullPath: '/$username/$repo/projects/'
      preLoaderRoute: typeof MainUsernameRepoProjectsIndexRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/issues/': {
      id: '/_main/$username/$repo/issues/'
      path: '/issues'
      fullPath: '/$username/$repo/issues/'
      preLoaderRoute: typeof MainUsernameRepoIssuesIndexRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/discussions/': {
      id: '/_main/$username/$repo/discussions/'
      path: '/discussions'
      fullPath: '/$username/$repo/discussions/'
      preLoaderRoute: typeof MainUsernameRepoDiscussionsIndexRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/tree/$': {
      id: '/_main/$username/$repo/tree/$'
      path: '/tree/$'
      fullPath: '/$username/$repo/tree/$'
      preLoaderRoute: typeof MainUsernameRepoTreeSplatRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/runs/$runId': {
      id: '/_main/$username/$repo/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/$username/$repo/runs/$runId'
      preLoaderRoute: typeof MainUsernameRepoRunsRunIdRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/releases/new': {
      id: '/_main/$username/$repo/releases/new'
      path: '/releases/new'
      fullPath: '/$username/$repo/releases/new'
      preLoaderRoute: typeof MainUsernameRepoReleasesNewRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/pulls/new': {
      id: '/_main/$username/$repo/pulls/new'
      path: '/pulls/new'
      fullPath: '/$username/$repo/pulls/new'
      preLoaderRoute: typeof MainUsernameRepoPullsNewRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/pulls/$number': {
      id: '/_main/$username/$repo/pulls/$number'
      path: '/pulls/$number'
      fullPath: '/$username/$repo/pulls/$number'
      preLoaderRoute: typeof MainUsernameRepoPullsNumberRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/projects/$projectId': {
      id: '/_main/$username/$repo/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/$username/$repo/projects/$projectId'
      preLoaderRoute: typeof MainUsernameRepoProjectsProjectIdRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/issues/new': {
      id: '/_main/$username/$repo/issues/new'
      path: '/issues/new'
      fullPath: '/$username/$repo/issues/new'
      preLoaderRoute: typeof MainUsernameRepoIssuesNewRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/issues/$number': {
      id: '/_main/$username/$repo/issues/$number'
      path: '/issues/$number'
      fullPath: '/$username/$repo/issues/$number'
      preLoaderRoute: typeof MainUsernameRepoIssuesNumberRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/discussions/new': {
      id: '/_main/$username/$repo/discussions/new'
      path: '/discussions/new'
      fullPath: '/$username/$repo/discussions/new'
      preLoaderRoute: typeof MainUsernameRepoDiscussionsNewRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/discussions/$number': {
      id: '/_main/$username/$repo/discussions/$number'
      path: '/discussions/$number'
      fullPath: '/$username/$repo/discussions/$number'
      preLoaderRoute: typeof MainUsernameRepoDiscussionsNumberRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/commits/$branch': {
      id: '/_main/$username/$repo/commits/$branch'
      path: '/$branch'
      fullPath: '/$username/$repo/commits/$branch'
      preLoaderRoute: typeof MainUsernameRepoCommitsBranchRouteImport
      parentRoute: typeof MainUsernameRepoCommitsRoute
    }
    '/_main/$username/$repo/blob/$': {
      id: '/_main/$username/$repo/blob/$'
      path: '/blob/$'
      fullPath: '/$username/$repo/blob/$'
      preLoaderRoute: typeof MainUsernameRepoBlobSplatRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/commits/$branch/': {
      id: '/_main/$username/$repo/commits/$branch/'
      path: '/'
      fullPath: '/$username/$repo/commits/$branch/'
      preLoaderRoute: typeof MainUsernameRepoCommitsBranchIndexRouteImport
      parentRoute: typeof MainUsernameRepoCommitsBranchRoute
    }
    '/_main/$username/$repo/releases/tag/$tag': {
      id: '/_main/$username/$repo/releases/tag/$tag'
      path: '/releases/tag/$tag'
      fullPath: '/$username/$repo/releases/tag/$tag'
      preLoaderRoute: typeof MainUsernameRepoReleasesTagTagRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/releases/$id/edit': {
      id: '/_main/$username/$repo/releases/$id/edit'
      path: '/releases/$id/edit'
      fullPath: '/$username/$repo/releases/$id/edit'
      preLoaderRoute: typeof MainUsernameRepoReleasesIdEditRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/commits/$branch/$oid': {
      id: '/_main/$username/$repo/commits/$branch/$oid'
      path: '/$oid'
      fullPath: '/$username/$repo/commits/$branch/$oid'
      preLoaderRoute: typeof MainUsernameRepoCommitsBranchOidRouteImport
      parentRoute: typeof MainUsernameRepoCommitsBranchRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainUsernameRepoCommitsBranchRouteChildren {
  MainUsernameRepoCommitsBranchOidRoute: typeof MainUsernameRepoCommitsBranchOidRoute
  MainUsernameRepoCommitsBranchIndexRoute: typeof MainUsernameRepoCommitsBranchIndexRoute
}

const MainUsernameRepoCommitsBranchRouteChildren: MainUsernameRepoCommitsBranchRouteChildren =
  {
    MainUsernameRepoCommitsBranchOidRoute:
      MainUsernameRepoCommitsBranchOidRoute,
    MainUsernameRepoCommitsBranchIndexRoute:
      MainUsernameRepoCommitsBranchIndexRoute,
  }

const MainUsernameRepoCommitsBranchRouteWithChildren =
  MainUsernameRepoCommitsBranchRoute._addFileChildren(
    MainUsernameRepoCommitsBranchRouteChildren,
  )

interface MainUsernameRepoCommitsRouteChildren {
  MainUsernameRepoCommitsBranchRoute: typeof MainUsernameRepoCommitsBranchRouteWithChildren
}

const MainUsernameRepoCommitsRouteChildren: MainUsernameRepoCommitsRouteChildren =
  {
    MainUsernameRepoCommitsBranchRoute:
      MainUsernameRepoCommitsBranchRouteWithChildren,
  }

const MainUsernameRepoCommitsRouteWithChildren =
  MainUsernameRepoCommitsRoute._addFileChildren(
    MainUsernameRepoCommitsRouteChildren,
  )

interface MainUsernameRepoRouteChildren {
  MainUsernameRepoCommitsRoute: typeof MainUsernameRepoCommitsRouteWithChildren
  MainUsernameRepoLabelsRoute: typeof MainUsernameRepoLabelsRoute
  MainUsernameRepoSettingsRoute: typeof MainUsernameRepoSettingsRoute
  MainUsernameRepoIndexRoute: typeof MainUsernameRepoIndexRoute
  MainUsernameRepoBlobSplatRoute: typeof MainUsernameRepoBlobSplatRoute
  MainUsernameRepoDiscussionsNumberRoute: typeof MainUsernameRepoDiscussionsNumberRoute
  MainUsernameRepoDiscussionsNewRoute: typeof MainUsernameRepoDiscussionsNewRoute
  MainUsernameRepoIssuesNumberRoute: typeof MainUsernameRepoIssuesNumberRoute
  MainUsernameRepoIssuesNewRoute: typeof MainUsernameRepoIssuesNewRoute
  MainUsernameRepoProjectsProjectIdRoute: typeof MainUsernameRepoProjectsProjectIdRoute
  MainUsernameRepoPullsNumberRoute: typeof MainUsernameRepoPullsNumberRoute
  MainUsernameRepoPullsNewRoute: typeof MainUsernameRepoPullsNewRoute
  MainUsernameRepoReleasesNewRoute: typeof MainUsernameRepoReleasesNewRoute
  MainUsernameRepoRunsRunIdRoute: typeof MainUsernameRepoRunsRunIdRoute
  MainUsernameRepoTreeSplatRoute: typeof MainUsernameRepoTreeSplatRoute
  MainUsernameRepoDiscussionsIndexRoute: typeof MainUsernameRepoDiscussionsIndexRoute
  MainUsernameRepoIssuesIndexRoute: typeof MainUsernameRepoIssuesIndexRoute
  MainUsernameRepoProjectsIndexRoute: typeof MainUsernameRepoProjectsIndexRoute
  MainUsernameRepoPullsIndexRoute: typeof MainUsernameRepoPullsIndexRoute
  MainUsernameRepoReleasesIndexRoute: typeof MainUsernameRepoReleasesIndexRoute
  MainUsernameRepoRunsIndexRoute: typeof MainUsernameRepoRunsIndexRoute
  MainUsernameRepoWorkflowsIndexRoute: typeof MainUsernameRepoWorkflowsIndexRoute
  MainUsernameRepoReleasesIdEditRoute: typeof MainUsernameRepoReleasesIdEditRoute
  MainUsernameRepoReleasesTagTagRoute: typeof MainUsernameRepoReleasesTagTagRoute
}

const MainUsernameRepoRouteChildren: MainUsernameRepoRouteChildren = {
  MainUsernameRepoCommitsRoute: MainUsernameRepoCommitsRouteWithChildren,
  MainUsernameRepoLabelsRoute: MainUsernameRepoLabelsRoute,
  MainUsernameRepoSettingsRoute: MainUsernameRepoSettingsRoute,
  MainUsernameRepoIndexRoute: MainUsernameRepoIndexRoute,
  MainUsernameRepoBlobSplatRoute: MainUsernameRepoBlobSplatRoute,
  MainUsernameRepoDiscussionsNumberRoute:
    MainUsernameRepoDiscussionsNumberRoute,
  MainUsernameRepoDiscussionsNewRoute: MainUsernameRepoDiscussionsNewRoute,
  MainUsernameRepoIssuesNumberRoute: MainUsernameRepoIssuesNumberRoute,
  MainUsernameRepoIssuesNewRoute: MainUsernameRepoIssuesNewRoute,
  MainUsernameRepoProjectsProjectIdRoute:
    MainUsernameRepoProjectsProjectIdRoute,
  MainUsernameRepoPullsNumberRoute: MainUsernameRepoPullsNumberRoute,
  MainUsernameRepoPullsNewRoute: MainUsernameRepoPullsNewRoute,
  MainUsernameRepoReleasesNewRoute: MainUsernameRepoReleasesNewRoute,
  MainUsernameRepoRunsRunIdRoute: MainUsernameRepoRunsRunIdRoute,
  MainUsernameRepoTreeSplatRoute: MainUsernameRepoTreeSplatRoute,
  MainUsernameRepoDiscussionsIndexRoute: MainUsernameRepoDiscussionsIndexRoute,
  MainUsernameRepoIssuesIndexRoute: MainUsernameRepoIssuesIndexRoute,
  MainUsernameRepoProjectsIndexRoute: MainUsernameRepoProjectsIndexRoute,
  MainUsernameRepoPullsIndexRoute: MainUsernameRepoPullsIndexRoute,
  MainUsernameRepoReleasesIndexRoute: MainUsernameRepoReleasesIndexRoute,
  MainUsernameRepoRunsIndexRoute: MainUsernameRepoRunsIndexRoute,
  MainUsernameRepoWorkflowsIndexRoute: MainUsernameRepoWorkflowsIndexRoute,
  MainUsernameRepoReleasesIdEditRoute: MainUsernameRepoReleasesIdEditRoute,
  MainUsernameRepoReleasesTagTagRoute: MainUsernameRepoReleasesTagTagRoute,
}

const MainUsernameRepoRouteWithChildren =
  MainUsernameRepoRoute._addFileChildren(MainUsernameRepoRouteChildren)

interface MainUsernameRouteChildren {
  MainUsernameRepoRoute: typeof MainUsernameRepoRouteWithChildren
  MainUsernameIndexOrgRoute: typeof MainUsernameIndexOrgRoute
  MainUsernameIndexRoute: typeof MainUsernameIndexRoute
}

const MainUsernameRouteChildren: MainUsernameRouteChildren = {
  MainUsernameRepoRoute: MainUsernameRepoRouteWithChildren,
  MainUsernameIndexOrgRoute: MainUsernameIndexOrgRoute,
  MainUsernameIndexRoute: MainUsernameIndexRoute,
}

const MainUsernameRouteWithChildren = MainUsernameRoute._addFileChildren(
  MainUsernameRouteChildren,
)

interface MainAdminRouteChildren {
  MainAdminIndexRoute: typeof MainAdminIndexRoute
  MainAdminUsersUserIdRoute: typeof MainAdminUsersUserIdRoute
  MainAdminApplicationsIndexRoute: typeof MainAdminApplicationsIndexRoute
  MainAdminAuditLogsIndexRoute: typeof MainAdminAuditLogsIndexRoute
  MainAdminDmcaIndexRoute: typeof MainAdminDmcaIndexRoute
  MainAdminGistsIndexRoute: typeof MainAdminGistsIndexRoute
  MainAdminOrganizationsIndexRoute: typeof MainAdminOrganizationsIndexRoute
  MainAdminReportsIndexRoute: typeof MainAdminReportsIndexRoute
  MainAdminRepositoriesIndexRoute: typeof MainAdminRepositoriesIndexRoute
  MainAdminRunnersIndexRoute: typeof MainAdminRunnersIndexRoute
  MainAdminSettingsIndexRoute: typeof MainAdminSettingsIndexRoute
  MainAdminStatsIndexRoute: typeof MainAdminStatsIndexRoute
  MainAdminUsersIndexRoute: typeof MainAdminUsersIndexRoute
  MainAdminUtilsIndexRoute: typeof MainAdminUtilsIndexRoute
}

const MainAdminRouteChildren: MainAdminRouteChildren = {
  MainAdminIndexRoute: MainAdminIndexRoute,
  MainAdminUsersUserIdRoute: MainAdminUsersUserIdRoute,
  MainAdminApplicationsIndexRoute: MainAdminApplicationsIndexRoute,
  MainAdminAuditLogsIndexRoute: MainAdminAuditLogsIndexRoute,
  MainAdminDmcaIndexRoute: MainAdminDmcaIndexRoute,
  MainAdminGistsIndexRoute: MainAdminGistsIndexRoute,
  MainAdminOrganizationsIndexRoute: MainAdminOrganizationsIndexRoute,
  MainAdminReportsIndexRoute: MainAdminReportsIndexRoute,
  MainAdminRepositoriesIndexRoute: MainAdminRepositoriesIndexRoute,
  MainAdminRunnersIndexRoute: MainAdminRunnersIndexRoute,
  MainAdminSettingsIndexRoute: MainAdminSettingsIndexRoute,
  MainAdminStatsIndexRoute: MainAdminStatsIndexRoute,
  MainAdminUsersIndexRoute: MainAdminUsersIndexRoute,
  MainAdminUtilsIndexRoute: MainAdminUtilsIndexRoute,
}

const MainAdminRouteWithChildren = MainAdminRoute._addFileChildren(
  MainAdminRouteChildren,
)

interface MainSettingsRouteChildren {
  MainSettingsMigrationsRoute: typeof MainSettingsMigrationsRoute
}

const MainSettingsRouteChildren: MainSettingsRouteChildren = {
  MainSettingsMigrationsRoute: MainSettingsMigrationsRoute,
}

const MainSettingsRouteWithChildren = MainSettingsRoute._addFileChildren(
  MainSettingsRouteChildren,
)

interface MainGistsIdRouteChildren {
  MainGistsIdEditRoute: typeof MainGistsIdEditRoute
}

const MainGistsIdRouteChildren: MainGistsIdRouteChildren = {
  MainGistsIdEditRoute: MainGistsIdEditRoute,
}

const MainGistsIdRouteWithChildren = MainGistsIdRoute._addFileChildren(
  MainGistsIdRouteChildren,
)

interface MainRouteChildren {
  MainUsernameRoute: typeof MainUsernameRouteWithChildren
  MainAboutRoute: typeof MainAboutRoute
  MainAdminRoute: typeof MainAdminRouteWithChildren
  MainCareersRoute: typeof MainCareersRoute
  MainContactRoute: typeof MainContactRoute
  MainExploreRoute: typeof MainExploreRoute
  MainFeaturesRoute: typeof MainFeaturesRoute
  MainPrivacyRoute: typeof MainPrivacyRoute
  MainSearchRoute: typeof MainSearchRoute
  MainSecurityRoute: typeof MainSecurityRoute
  MainSettingsRoute: typeof MainSettingsRouteWithChildren
  MainTermsRoute: typeof MainTermsRoute
  MainIndexRoute: typeof MainIndexRoute
  MainGistsIdRoute: typeof MainGistsIdRouteWithChildren
  MainGistsNewRoute: typeof MainGistsNewRoute
  MainOrganizationsNewRoute: typeof MainOrganizationsNewRoute
  MainGistsIndexRoute: typeof MainGistsIndexRoute
  MainNewImportIndexRoute: typeof MainNewImportIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainUsernameRoute: MainUsernameRouteWithChildren,
  MainAboutRoute: MainAboutRoute,
  MainAdminRoute: MainAdminRouteWithChildren,
  MainCareersRoute: MainCareersRoute,
  MainContactRoute: MainContactRoute,
  MainExploreRoute: MainExploreRoute,
  MainFeaturesRoute: MainFeaturesRoute,
  MainPrivacyRoute: MainPrivacyRoute,
  MainSearchRoute: MainSearchRoute,
  MainSecurityRoute: MainSecurityRoute,
  MainSettingsRoute: MainSettingsRouteWithChildren,
  MainTermsRoute: MainTermsRoute,
  MainIndexRoute: MainIndexRoute,
  MainGistsIdRoute: MainGistsIdRouteWithChildren,
  MainGistsNewRoute: MainGistsNewRoute,
  MainOrganizationsNewRoute: MainOrganizationsNewRoute,
  MainGistsIndexRoute: MainGistsIndexRoute,
  MainNewImportIndexRoute: MainNewImportIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
  RateLimitedRoute: RateLimitedRoute,
  SitemapRoute: SitemapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
