import { View, Text, ScrollView, RefreshControl, ActivityIndicator, StyleSheet, Pressable } from "react-native";

export const markdownStyles = StyleSheet.create({
  body: {
    color: "#ffffff",
    fontSize: 12,
    lineHeight: 25.5,
    fontFamily: "System",
  },
  heading1: {
    fontSize: 28,
    fontWeight: "600",
    // marginTop: 24,
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
    color: "#ffffff",
    lineHeight: 36.4,
  },
  heading2: {
    fontSize: 22.4,
    fontWeight: "600",
    marginTop: 12,
    marginBottom: 12,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
    color: "#ffffff",
    lineHeight: 29.12,
  },
  heading3: {
    fontSize: 19.2,
    fontWeight: "600",
    marginTop: 12,
    marginBottom: 12,
    color: "#ffffff",
    lineHeight: 24.96,
  },
  heading4: {
    fontSize: 16,
    fontWeight: "600",
    marginTop: 12,
    marginBottom: 12,
    color: "#ffffff",
    lineHeight: 20.8,
  },
  heading5: {
    fontSize: 14.4,
    fontWeight: "600",
    marginTop: 12,
    marginBottom: 12,
    color: "#ffffff",
    lineHeight: 18.72,
  },
  heading6: {
    fontSize: 13.6,
    fontWeight: "600",
    marginTop: 12,
    marginBottom: 12,
    color: "rgba(255, 255, 255, 0.6)",
    lineHeight: 17.68,
  },
  paragraph: {
    marginTop: 0,
    marginBottom: 16,
    fontSize: 12,
    color: "#ffffff",
  },
  link: {
    color: "#60a5fa",
    textDecorationLine: "none",
  },
  strong: {
    fontWeight: "600",
    color: "#ffffff",
  },
  em: {
    fontStyle: "italic",
    color: "#ffffff",
  },
  code_inline: {
    fontSize: 12,
    fontFamily: "GeistMono",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    paddingHorizontal: 2,
    paddingVertical: 2,
    borderRadius: 3,
    color: "#ffffff",
  },
  code_block: {
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    borderWidth: 1,
    fontSize: 12,
    fontFamily: "GeistMono",
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 6,
    marginTop: 16,
    marginBottom: 16,
    overflow: "scroll",
    padding: 8,
  },
  fence: {
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 6,
    marginTop: 16,
    marginBottom: 16,
    overflow: "hidden",
    padding: 16,
    fontFamily: "GeistMono",
    fontSize: 12,
  },
  list_item: {
    marginTop: 4,
    color: "#ffffff",
  },
  bullet_list: {
    paddingLeft: 6,
    marginTop: 0,
    marginBottom: 16,
  },
  ordered_list: {
    paddingLeft: 6,
    marginTop: 0,
    marginBottom: 16,
  },
  blockquote: {
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 0,
    paddingBottom: 0,
    marginTop: 0,
    marginBottom: 16,
    borderLeftWidth: 3,
    borderLeftColor: "#60a5fa",
    backgroundColor: "rgba(96, 165, 250, 0.1)",
    color: "rgba(255, 255, 255, 0.7)",
  },
  hr: {
    height: 1,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    marginTop: 32,
    marginBottom: 32,
  },
  table: {
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 6,
    marginTop: 0,
    marginBottom: 16,
    overflow: "hidden",
  },
  thead: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
  },
  th: {
    padding: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    fontWeight: "600",
    color: "#ffffff",
  },
  td: {
    padding: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    color: "#ffffff",
  },
  tr: {
    backgroundColor: "rgba(0, 0, 0, 0.2)",
  },
  image: {
    maxWidth: "100%",
    borderRadius: 6,
    marginTop: 16,
    marginBottom: 16,
  },
});
